export enum TabsName {
  weibo = 'weibo',
  // weibo2 = 'weibo2',
  baidu = 'baidu',
  toutiao = 'toutiao',
  douyin = 'douyin',
  douyin_hotlist = 'douyin_hotlist',
  zhihu = 'zhihu',
  wangyi = 'wangyi',
  // muzi = 'muzi',
  tengxun = 'tengxun',
  // xinlang = 'xinlang',
  fenghuang = 'fenghuang',
  // juejin = 'juejin',
  bilibili = 'bilibili',
}

export const TabsList = [
  // {
  //   name: TabsName.weibo,
  //   title: '微博热搜',
  //   show: true,
  //   url: 'https://m.weibo.cn/p/106003type=25&t=3&disable_hot=1&filter_type=realtimehot',
  //   builtIn: true,
  //   icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/weibo.png',
  // },
  {
    name: TabsName.weibo,
    title: '微博热搜',
    show: true,
    url: 'https://s.weibo.com/top/summary?cate=realtimehot',
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/weibo.png',
  },
  {
    name: TabsName.baidu,
    title: '百度热搜',
    show: true,
    url: 'https://top.baidu.com/board?tab=realtime',
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/baidu.png',
  },
  {
    name: TabsName.toutiao,
    title: '头条热榜',
    show: true,
    url: 'https://api.toutiaoapi.com/feoffline/hotspot_and_local/html/hot_list/index.html',
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/toutiao.png',
    builtIn: true,
  },
  {
    name: TabsName.tengxun,
    title: '腾讯热榜',
    show: true,
    url: 'https://view.inews.qq.com/ranking?rankingtabtype=1',
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/tengxun.png',
  },
  {
    name: TabsName.douyin,
    title: '抖音热点',
    show: true,
    url: 'https://www.douyin.com/share/billboard',
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/douyin.png',
    builtIn: true,
  },
  {
    name: TabsName.douyin_hotlist,
    title: '抖音热榜',
    show: true,
    url: 'https://so-landing.douyin.com/landings/hotlist',
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/douyin.png',
    builtIn: true,
  },
  // {
  //   name: TabsName.xinlang,
  //   title: '新浪热榜',
  //   show: true,
  //   url: 'https://sinanews.sina.cn/h5/top_news_list.d.html',
  //   builtIn: true,
  //   icon: 'https://images.icon-icons.com/2037/PNG/512/media_social_weibo_icon_124251.png',
  // },
  {
    name: TabsName.wangyi,
    title: '网易热榜',
    show: true,
    url: 'https://wp.m.163.com/163/html/newsapp/hot-content/index.html?version=searchFirstTab',
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/wangyi.png',
  },
  {
    name: TabsName.zhihu,
    title: '知乎热榜',
    show: true,
    url: 'https://www.zhihu.com/billboard',
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/zhihu.png',
  },
  {
    name: TabsName.bilibili,
    title: 'bilibili热搜',
    url: 'https://www.bilibili.com/blackboard/activity-trending-topic.html',
    show: true,
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/bilibili.png',
  },
  {
    name: TabsName.fenghuang,
    title: '凤凰热榜',
    url: 'https://ishare.ifeng.com/hotNewsRank/',
    show: true,
    builtIn: true,
    icon: 'https://pub-81d777fc2e8043689e156f1e88c01386.r2.dev/fenghuang.png',
  },
]

export const getTabUrl = (name: string) => {
  return TabsList.find(t => t.name === name)?.url
}
